name:                haskell-collagol 
version:             0.1.0.0
github:              "Uriopass/Collagol"
license:             BSD3
author:              "Pâris DOUADY"
maintainer:          "paris (dot) douady [at] hotmail.fr"
copyright:           "2019"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/Uriopass/Collagol#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- mtl
- websockets

executables:
  haskell-collagol-exe:
    main:                Main.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -W
